[server]
enableCORS = false
enableXsrfProtection = false

[browser]
serverAddress = "localhost"
serverPort = 8501

[runner]
magicEnabled = true

[theme]
primaryColor = "#FFE600"
backgroundColor = "#2E2E38"
secondaryBackgroundColor = "#747480"
textColor = "#FFFFFF"

[logger]
level = "info"

[client]
showErrorDetails = true

[global]
developmentMode = true